repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-ast
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: debug-statements
    - id: fix-encoding-pragma
    - id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
